config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register'}
  resources :portfolios, except: [:show]

  get 'angular-items', to: 'portfolios#angular'

  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'#chnages the route to portfolio/:id instead of portfolios/:id. must also change the proper index file


  # names are connected to the pages_controller file and veiws files
  

  get 'about-me', to: 'pages#about'

  get 'contact', to:'pages#contact'

  resources :blogs do
    member do
      get :toggle_status
    end
  end


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'pages#home'#replacing get 'pages/home' and the localhost:3000
end

app/models/portfolio.rb
class Portfolio < ApplicationRecord
  include Placeholder
  has_many :technologies
  accepts_nested_attributes_for :technologies, reject_if: lambda {|attrs| attrs['name'].blank?}

  validates_presence_of :title, :body, :main_image, :thumb_image
  def self.angular
    where(subtitle: "Angular")
  end

  scope :ruby_on_rails_portfolio_items, -> { where(subtitle: 'Ruby on Rails')}

  after_initialize :set_defaults

  def set_defaults
    self.main_image ||= Placeholder.image_generator(height: 600, width: 400)
    self.thumb_image ||= Placeholder.image_generator(height: 350, width: 200)
  end
end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
  layout 'portfolio'

  #this is generally used when you want to list out a number of items
  def index
    #class variable = 
    #model veiw controller
    #calling the model(Portfolio.all) inside of the controller(this file)
    #portfolio items now available to the view
    #now create a new file in views
    @portfolio_items = Portfolio.all
  end

  def angular
    @angular_portfolio_items = Portfolio.angular
  end

  def new# this must have a corresponding veiws file to call from
    @portfolio_item = Portfolio.new
    3.times {@portfolio_item.technologies.build}
  end

  def create
    @portfolio_item = Portfolio.new(portfolio_params)#this is another method

    respond_to do |format|
      if @portfolio_item.save
        format.html { redirect_to portfolios_path, notice: 'Portfolio was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def edit
    @portfolio_item = Portfolio.find(params[:id])

  end

  def update
    @portfolio_item = Portfolio.find(params[:id])

    respond_to do |format|
      if @portfolio_item.update(portfolio_params)
        format.html { redirect_to portfolios_path, notice: 'Portfolio item was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def show
    @portfolio_item = Portfolio.find(params[:id])
  end

  def destroy
    @portfolio_item = Portfolio.find(params[:id])


    @portfolio_item.destroy
    respond_to do |format|
      format.html { redirect_to portfolios_url, notice: 'Portfolio item was successfully destroyed.' }
    end
  end

  private

  def portfolio_params
    params.require(:portfolio).permit(
      :title,
      :subtitle,
      :body,
      technologies_attributes: [:name]
      )
  end
end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
end

app/views/portfolios/_form.html.erb
<%= form_with(model: @portfolio_item, local: true) do |form|%>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :portfolio_title %>
  </div>

    <div class="field">
    <%= form.label :subtitle %>
    <%= form.text_field :subtitle, id: :portfolio_subtitle %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body, id: :portfolio_body %>
  </div>

  <ul>
    <%= form.fields_for :technologies do |technology_form| %>
      <li>
        <%= technology_form.label :name %>
        <%= technology_form.text_field :name %>
      </li>
    <% end %>
  </ul>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/portfolios/_portfolio_item.html.erb
  <p><%= link_to portfolio_item.title, portfolio_show_path(portfolio_item.id) %></p>
  <p><%= portfolio_item.subtitle %></p>
  <p><%= portfolio_item.body %></p>
  <p><%= image_tag portfolio_item.thumb_image if !portfolio_item.thumb_image.nil? %></p>
  <%= link_to "Edit",edit_portfolio_path(portfolio_item.id) %>
  <%= link_to "Delete",portfolio_path(portfolio_item.id), method: :delete, data: { confirm: 'Are you sure?'} %>

app/views/portfolios/angluar.html.erb
<h1>Angular Portfolio Items</h1>
<!-- <%#emebed ruby%> it is what the .erb is about -->
<!-- where did the portfolios_items class variable(array) come from. Also something about an equals sign before the percent sign so that it can render the information on the page -->

<!--<a href="portfolios/new" >Create New Item</a>-->

<%= link_to "Create New Item", new_portfolio_path %>

<p><%= new_portfolio_path %></p>

<% @angular_portfolio_items.each do |portfolio_item| %>
  <p><%= link_to portfolio_item.title, portfolio_show_path(portfolio_item.id) %></p>
  <p><%= portfolio_item.subtitle %></p>
  <p><%= portfolio_item.body %></p>
  <p><%= image_tag portfolio_item.thumb_image if !portfolio_item.thumb_image.nil? %></p>
  <%= link_to "Edit",edit_portfolio_path(portfolio_item.id) %>
  <%= link_to "Delete",portfolio_path(portfolio_item.id), method: :delete, data: { confirm: 'Are you sure?'} %>
<%end%>

app/views/portfolios/angular.html.erb
<h1>Angular Portfolio Items</h1>
<!-- <%#emebed ruby%> it is what the .erb is about -->
<!-- where did the portfolios_items class variable(array) come from. Also something about an equals sign before the percent sign so that it can render the information on the page -->

<!--<a href="portfolios/new" >Create New Item</a>-->

<%= link_to "Create New Item", new_portfolio_path %>

<p><%= new_portfolio_path %></p>

<% @angular_portfolio_items.each do |portfolio_item| %>
  <p><%= link_to portfolio_item.title, portfolio_show_path(portfolio_item.id) %></p>
  <p><%= portfolio_item.subtitle %></p>
  <p><%= portfolio_item.body %></p>
  <p><%= image_tag portfolio_item.thumb_image if !portfolio_item.thumb_image.nil? %></p>
  <%= link_to "Edit",edit_portfolio_path(portfolio_item.id) %>
  <%= link_to "Delete",portfolio_path(portfolio_item.id), method: :delete, data: { confirm: 'Are you sure?'} %>
<%end%>

app/views/portfolios/edit.html.erb
<h1> Edit Portfolio Item</h1>

<%= render 'form', portfolio_item: @portfolio_item %>

app/views/portfolios/index.html.erb
<h1>Portfolio Items</h1>
<!-- <%#emebed ruby%> it is what the .erb is about -->
<!-- where did the portfolios_items class variable(array) come from. Also something about an equals sign before the percent sign so that it can render the information on the page -->

<!--<a href="portfolios/new" >Create New Item</a>-->

<%= link_to "Create New Item", new_portfolio_path %>


<%= render partial: 'portfolio_item', collection: @portfolio_items %>

app/views/portfolios/new.html.erb
<h1> Create a New Portfolio Item</h1>

<%= render 'form', portfolio_item: @portfolio_item %>

app/views/portfolios/show.html.erb
<%= image_tag @portfolio_item.main_image %>

<h1> <%= @portfolio_item.title %></h1>

<em><%= @portfolio_item.subtitle %></em>

<p><%= @portfolio_item.body%>

<h2>Technologies Used:</h2>
<% @portfolio_item.technologies.each do |t| %>
<p><%= t.name%><p>
<% end %>

<!––This is connected to Application controllers/concerns––>
<%= session.inspect %>

<% session[:source] %>